### ISSUE TITLE
Streaming Mode, Stream During Playback checked, meshes during render not updating?

### ISSUE THREAD

**Issue by WillemKauf** [neverhood311/Stop-motion-OBJ#124] opened 2021-02-17 15:33 UTC
Hi,

I have my ~400 frame sequence imported with streaming mode enabled, a cache size of 5, and stream during playback enabled.

I left my computer on overnight to render, but when I came back every rendered image past frame 5 was the same mesh as frame 5. Is there something I missed here?

Thanks in advance.

**Comment by neverhood311** [comment] 2021-02-17 15:43
A few questions:
Which version of Blender?
Which version of Stop Motion OBJ?
What file type are you loading? (obj? ply? stl?)
Are you rendering through the UI or via the command line?
Would you be able to provide 2 or 3 of the meshes from your sequence so I can do some testing on my end?

**Comment by WillemKauf** [comment] 2021-02-17 15:49
Which version of Blender?
>Which version of Stop Motion OBJ?

2.91.0

>What file type are you loading? (obj? ply? stl?)

PLY.

>Are you rendering through the UI or via the command line?

UI.

>Would you be able to provide 2 or 3 of the meshes from your sequence so I can do some testing on my end?

Yep!
[files.zip](https://github.com/neverhood311/Stop-motion-OBJ/files/5996816/files.zip)

**Comment by neverhood311** [comment] 2021-02-17 16:19
You said you were importing .ply files? The files you provided were .csv files. I'm not sure what to do with these.

Are you able to try Blender 2.83.12 LTS? A few minor things have changed from 2.83->2.9x and 2.91 doesn't always play nicely with Stop Motion OBJ, unfortunately.

**Comment by WillemKauf** [comment] 2021-02-17 16:22
Oh god, my mistake. Accidentally sorted by file type in my directory and didn't notice.

I can try Blender 2.83.

[files.zip](https://github.com/neverhood311/Stop-motion-OBJ/files/5997055/files.zip)

**Comment by WillemKauf** [comment] 2021-02-17 16:31
Looks like Blender 2.83 was able to make it past my cache size and streams meshes correctly. Perhaps it is a bug with 2.91.0!

Thank you for the timely responses.

**Comment by neverhood311** [comment] 2021-02-18 16:01
Closing since this is a duplicate of #124

**Closed by neverhood311** 2021-02-18 16:01 UTC
Labels: bug
